//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 03:27:52 PM CET 
//


package com.telespazio.hsaf.ordermanagement.orderlist.xsd.autogeneratedClasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telespazio.hsaf.ordermanagement.eumetsatOrderList.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Order_QNAME = new QName("", "order");
    private final static QName _Orderlist_QNAME = new QName("", "orderlist");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telespazio.hsaf.ordermanagement.eumetsatOrderList.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Orderlist }
     * 
     */
    public Orderlist createOrderlist() {
        return new Orderlist();
    }

    /**
     * Create an instance of {@link FtpOptions }
     * 
     */
    public FtpOptions createFtpOptions() {
        return new FtpOptions();
    }

    /**
     * Create an instance of {@link TimeOfInterest }
     * 
     */
    public TimeOfInterest createTimeOfInterest() {
        return new TimeOfInterest();
    }

    /**
     * Create an instance of {@link GasSubsetting }
     * 
     */
    public GasSubsetting createGasSubsetting() {
        return new GasSubsetting();
    }

    /**
     * Create an instance of {@link PFDUnit }
     * 
     */
    public PFDUnit createPFDUnit() {
        return new PFDUnit();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link RegionOfInterest }
     * 
     */
    public RegionOfInterest createRegionOfInterest() {
        return new RegionOfInterest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link BulkDates }
     * 
     */
    public BulkDates createBulkDates() {
        return new BulkDates();
    }

    /**
     * Create an instance of {@link UMARFMetadataField }
     * 
     */
    public UMARFMetadataField createUMARFMetadataField() {
        return new UMARFMetadataField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Orderlist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderlist")
    public JAXBElement<Orderlist> createOrderlist(Orderlist value) {
        return new JAXBElement<Orderlist>(_Orderlist_QNAME, Orderlist.class, null, value);
    }

}
