//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 03:27:52 PM CET 
//


package com.telespazio.hsaf.ordermanagement.orderlist.xsd.autogeneratedClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outputType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="outputType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CDR"/>
 *     &lt;enumeration value="DVD"/>
 *     &lt;enumeration value="FTP"/>
 *     &lt;enumeration value="DAT"/>
 *     &lt;enumeration value="DLT"/>
 *     &lt;enumeration value="NET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "outputType")
@XmlEnum
public enum OutputType {

    CDR,
    DVD,
    FTP,
    DAT,
    DLT,
    NET;

    public String value() {
        return name();
    }

    public static OutputType fromValue(String v) {
        return valueOf(v);
    }

}
