//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 03:27:52 PM CET 
//


package com.telespazio.hsaf.ordermanagement.orderlist.xsd.autogeneratedClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PFDUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PFDUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productID" type="{}productID"/>
 *         &lt;element name="gasSubsetting" type="{}gasSubsetting" minOccurs="0"/>
 *         &lt;element name="regionOfInterest" type="{}RegionOfInterest" minOccurs="0"/>
 *         &lt;element name="timeOfInterest" type="{}TimeOfInterest" minOccurs="0"/>
 *         &lt;element name="additionalInfo" type="{}additionalInfo"/>
 *         &lt;element name="format" type="{}formatType" minOccurs="0"/>
 *         &lt;element name="compression" type="{}compressionType" minOccurs="0"/>
 *         &lt;element name="output" type="{}outputType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PFDUnit", propOrder = {
    "productID",
    "gasSubsetting",
    "regionOfInterest",
    "timeOfInterest",
    "additionalInfo",
    "format",
    "compression",
    "output"
})
public class PFDUnit {

    @XmlElement(required = true)
    protected String productID;
    protected GasSubsetting gasSubsetting;
    protected RegionOfInterest regionOfInterest;
    protected TimeOfInterest timeOfInterest;
    @XmlElement(required = true)
    protected AdditionalInfo additionalInfo;
    protected FormatType format;
    protected CompressionType compression;
    @XmlElement(required = true)
    protected OutputType output;

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductID(String value) {
        this.productID = value;
    }

    /**
     * Gets the value of the gasSubsetting property.
     * 
     * @return
     *     possible object is
     *     {@link GasSubsetting }
     *     
     */
    public GasSubsetting getGasSubsetting() {
        return gasSubsetting;
    }

    /**
     * Sets the value of the gasSubsetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasSubsetting }
     *     
     */
    public void setGasSubsetting(GasSubsetting value) {
        this.gasSubsetting = value;
    }

    /**
     * Gets the value of the regionOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link RegionOfInterest }
     *     
     */
    public RegionOfInterest getRegionOfInterest() {
        return regionOfInterest;
    }

    /**
     * Sets the value of the regionOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionOfInterest }
     *     
     */
    public void setRegionOfInterest(RegionOfInterest value) {
        this.regionOfInterest = value;
    }

    /**
     * Gets the value of the timeOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link TimeOfInterest }
     *     
     */
    public TimeOfInterest getTimeOfInterest() {
        return timeOfInterest;
    }

    /**
     * Sets the value of the timeOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeOfInterest }
     *     
     */
    public void setTimeOfInterest(TimeOfInterest value) {
        this.timeOfInterest = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfo }
     *     
     */
    public AdditionalInfo getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfo }
     *     
     */
    public void setAdditionalInfo(AdditionalInfo value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link FormatType }
     *     
     */
    public FormatType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatType }
     *     
     */
    public void setFormat(FormatType value) {
        this.format = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link CompressionType }
     *     
     */
    public CompressionType getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompressionType }
     *     
     */
    public void setCompression(CompressionType value) {
        this.compression = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link OutputType }
     *     
     */
    public OutputType getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputType }
     *     
     */
    public void setOutput(OutputType value) {
        this.output = value;
    }

}
